version: '3.8'

services:
  mensageria:
    image: herdneysantos/mensageria-app:latest
    environment:
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=sua_porta_db
      - DB_USER=postgres
      - DB_PASSWORD=sua_senha_bd
      - DB_NAME=mensageria
      - OPENAI_API_KEY=sk-sua-chave-aqui
    networks:
      - sua_rede_docker # Rede externa onde o Traefik roda
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # Habilitar Traefik
        - "traefik.enable=true"
        
        # Router: HTTP (Redirecionamento para HTTPS opcional, ajuste conforme seu setup)
        - "traefik.http.routers.mensageria-http.rule=Host(`app.seudominio.com.br`)"
        - "traefik.http.routers.mensageria-http.entrypoints=web"
        
        # Router: HTTPS
        - "traefik.http.routers.mensageria.rule=Host(`app.seudominio.com.br`)"
        - "traefik.http.routers.mensageria.entrypoints=websecure"
        - "traefik.http.routers.mensageria.tls.certresolver=myresolver" # Ajuste para o nome do seu resolver (ex: letsencrypt)
        
        # Service: Porta da aplicação
        - "traefik.http.services.mensageria.loadbalancer.server.port=3001"

networks:
  sua_rede_docker:
    external: true
